### ISSUE TITLE
[BUG] `PydanticDeprecatedSince20` coming from `DeepSpeedZeroConfig`

### ISSUE THREAD

**Issue by jamesbraza** [deepspeedai/DeepSpeed#7149]
**Describe the bug**

`DeepSpeedZeroConfig` here: https://github.com/deepspeedai/DeepSpeed/blob/v0.16.4/deepspeed/runtime/zero/config.py#L86

Leads to this warning:

```none
.venv/lib/python3.12/site-packages/pydantic/fields.py:1042
  /home/james/code/molr1/.venv/lib/python3.12/site-packages/pydantic/fields.py:1042: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'new_param'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.10/migration/
```

**To Reproduce**

Use `deepspeed` with `pytest` and `pydantic>=2`:

```python
import pydantic
from deepspeed.runtime.zero.config import DeepSpeedZeroConfig  # noqa: F401
from packaging.version import parse


def test_stub() -> None:
    assert parse(pydantic.__version__).major == 2, "Deprecation comes from Pydantic v2"
```

**Expected behavior**

No deprecation warnings from the above code snippet.

**Screenshots**

N/a

**System info (please complete the following information):**

 - Python version 3.12

**Docker context**

N/a

**Additional context**

You can disable this warning in `pyproject.toml` via:

```toml
[tool.pytest.ini_options]
filterwarnings = [
    'ignore:Using extra keyword arguments on `Field` is deprecated:pydantic.PydanticDeprecatedSince20',  # SEE: https://github.com/deepspeedai/DeepSpeed/issues/7149
]
```
